### PR TITLE
Catch missing queue exeception on queueExists

### LINKED ISSUE #62: SQS exception while checking for queue existence
As a last resort, the AWS provider uses SqsClient::getQueueUrl() to check for the existence of a queue - however, that method throws an exception if the queue does not exist. See https://github.com/aws/aws-sdk-php/blob/master/src/Aws/Sqs/Resources/sqs-2012-11-05.php#L483

### PR DESCRIPTION
**Pull request by sdufel**
Fixes #62

### CODE REVIEW

File: src/Provider/AwsProvider.php [hunk 1]
```diff
@@ -311,13 +312,15 @@ public function queueExists()
...
+        try {
+            $result = $this->sqs->getQueueUrl([
+                'QueueName' => $this->getNameWithPrefix()
+            ]);
 
-        if($this->queueUrl = $result->get('QueueUrl')) {
-            return true;
-        }
+            if ($this->queueUrl = $result->get('QueueUrl')) {
+                return true;
```
Comment (kmfk) [inline src/Provider/AwsProvider.php]: Do you mind setting the queueUrl back into cache here?  Its an attempt to keep us from having to hit the API to keep track of it, any time we do, let's reset the cache.
